export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL'

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST'
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'

export const BOOKING_LIST_MY_REQUEST = 'BOOKING_LIST_MY_REQUEST'
export const BOOKING_LIST_MY_SUCCESS = 'BOOKING_LIST_MY_SUCCESS'
export const BOOKING_LIST_MY_FAIL = 'BOOKING_LIST_MY_FAIL'
export const BOOKING_LIST_MY_RESET = 'BOOKING_LIST_MY_RESET'