export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST'
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS'
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL'

export const HOTEL_DETAILS_REQUEST = 'HOTEL_DETAILS_REQUEST'
export const HOTEL_DETAILS_SUCCESS = 'HOTEL_DETAILS_SUCCESS'
export const HOTEL_DETAILS_FAIL = 'HOTEL_DETAILS_FAIL'

export const HOTEL_CREATE_REVIEW_REQUEST = 'HOTEL_CREATE_REVIEW_REQUEST'
export const HOTEL_CREATE_REVIEW_SUCCESS = 'HOTEL_CREATE_REVIEW_SUCCESS'
export const HOTEL_CREATE_REVIEW_FAIL = 'HOTEL_CREATE_REVIEW_FAIL'
export const HOTEL_CREATE_REVIEW_RESET = 'HOTEL_CREATE_REVIEW_RESET'